# Generated by Django 4.1.2 on 2022-10-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campanha",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("condominios", "CONDOMÍNIOS"),
                            ("empresas", "EMPRESAS"),
                            ("redes", "REDES"),
                            ("prestacao", "PRESTAÇÃO DE SERVIÇOS"),
                        ],
                        default="condominios",
                        max_length=30,
                        verbose_name="Tipo de Campanha",
                    ),
                ),
                ("nome", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Cadastrado em"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Modificado em"
                    ),
                ),
                (
                    "envios",
                    models.ManyToManyField(
                        to="empresas.empresa", verbose_name="Empresas"
                    ),
                ),
            ],
        ),
    ]
